### 1. Iniciar sesión como Admin para obtener el Token
# @name loginAdmin
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "12345Password"
}

### 2. Guardar Token del Admin
@adminToken = {{loginAdmin.response.body.authorizationToken}}

### 3. GET usuarios (Solo Admin puede ver la lista)
GET http://localhost:3000/api/users
Authorization: Bearer {{adminToken}}

### 4. POST crear usuario empleado/mozo (Solo Admin puede crearlo)
POST http://localhost:3000/api/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "username": "mozo1",
    "password": "12345Password",
    "displayName": "Lucas Mozo",
    "email": "lucas@cafeteria.com",
    "role": "empleado"
}

### 5. POST crear usuario cliente (Solo Admin puede crearlo)
POST http://localhost:3000/api/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "username": "cliente1",
    "password": "12345Password",
    "displayName": "Juan Cliente",
    "email": "juan@gmail.com",
    "role": "cliente"
}

### 6. PATCH actualizar usuario (Solo Admin)
PATCH http://localhost:3000/api/users/mozo1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "displayName": "Lucas Mozo Actualizado"
}

### 7. DELETE eliminar usuario (Solo Admin)
DELETE http://localhost:3000/api/users/mozo1
Authorization: Bearer {{adminToken}}